on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
          flake8
          mypy
      - name: Lint, format and static type check
        run: |
          poetry run black --check.
          petry run flake8
          poetry run mypy
      - name: Test
        run: |
          poetry run pytest
        env:
          ENV: test
